build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  only:
      - test
  tags:
      - k8s-test-udp

deploy:
    image: alpine/helm:3.4.2
    stage: deploy
    script:
        - >
            helm --namespace=default upgrade --install gamificacion-api helm-deployment/ 
            --set image.repository=$CI_REGISTRY_IMAGE 
            --set image.tag=$CI_COMMIT_SHA
            --set image.dbsecrets="database-pg"
            --set imagePullSecrets[0].name="regcred"
    only:
        - test
    tags:
        - k8s-test-udp
